package com.dentalwings.approvalbot.observability;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import com.dentalwings.approvalbot.ado.AdoClient;
import com.dentalwings.approvalbot.ado.AdoCommentResult;
import com.dentalwings.approvalbot.ado.AdoIdentity;
import com.dentalwings.approvalbot.ado.AdoPatchResult;
import com.dentalwings.approvalbot.ado.AdoWorkItem;
import com.dentalwings.approvalbot.ado.AdoWorkItemKey;
import com.dentalwings.approvalbot.ado.AdoWorkItemRevision;
import com.dentalwings.approvalbot.ado.http.AzureDevOpsHttpClient;
import com.dentalwings.approvalbot.config.ProjectApprovalConfig;
import com.dentalwings.approvalbot.domain.PatchOperation;
import com.dentalwings.approvalbot.domain.WorkflowDecision;
import com.dentalwings.approvalbot.idempotency.IdempotentWorkItemProcessor;
import com.dentalwings.approvalbot.idempotency.InMemoryProcessedEventStore;
import com.dentalwings.approvalbot.processing.ProcessWorkItemCommand;
import com.dentalwings.approvalbot.processing.WorkItemProcessingResult;
import com.dentalwings.approvalbot.processing.WorkItemProcessingService;
import com.dentalwings.approvalbot.processing.pipeline.WebhookEventProcessingPipeline;
import com.dentalwings.approvalbot.processing.pipeline.WebhookProcessingStatus;
import com.dentalwings.approvalbot.queue.InMemoryWorkItemQueue;
import com.dentalwings.approvalbot.queue.QueuedWorkItemProcessor;
import com.dentalwings.approvalbot.webhook.AdoWebhookEvent;
import com.dentalwings.approvalbot.webhook.EventClassifier;
import com.dentalwings.approvalbot.workflow.WorkflowEngine;
import com.dentalwings.approvalbot.workflow.comment.CommentBuilder;
import com.dentalwings.approvalbot.workflow.patch.PatchBuilder;
import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.web.reactive.function.client.ClientResponse;
import reactor.core.publisher.Mono;

import static org.assertj.core.api.Assertions.assertThat;

class SandboxObservabilityLoggingTest {

    private static final AdoWorkItemKey KEY = new AdoWorkItemKey("org", "ProjectA", 123);

    @Test
    void httpClientLogsDoNotExposePatOrAuthorizationHeader() {
        var logs = captureLogs(() -> {
            var client = AzureDevOpsHttpClient.forExchangeFunction(
                    request -> Mono.just(ClientResponse.create(HttpStatus.CONFLICT).body("{}").build()),
                    "SECRET_PAT_VALUE");

            client.patchWorkItem(KEY,
                    List.of(PatchOperation.testRevision(10), PatchOperation.replaceField("System.State", "In Review")));
        });

        assertThat(logs).contains("operation=patchWorkItem").contains("httpStatus=409").contains("retryable=true")
                .contains("operationPaths=[/rev, /fields/System.State]").doesNotContain("SECRET_PAT_VALUE")
                .doesNotContain("Authorization").doesNotContain("Basic ").doesNotContain("In Review");
    }

    @Test
    void skippedEventsLogClassificationReasonsWithoutPayloadDump() {
        var logs = captureLogs(() -> {
            var pipeline = pipeline();

            pipeline.process(event("ProjectA", "Test Case", "bot@example.com"), config(true, "Test Case"));
            pipeline.process(event("ProjectA", "Test Case", "human@example.com"), config(false, "Test Case"));
            pipeline.process(event("ProjectA", "Bug", "human@example.com"), config(true, "Test Case"));
        });

        assertThat(logs).contains("SKIPPED_BOT_EVENT").contains("Event was generated by the bot.")
                .contains("SKIPPED_DISABLED_PROJECT").contains("Project is disabled.")
                .contains("SKIPPED_UNSUPPORTED_WORK_ITEM_TYPE").contains("Work item type is unsupported.")
                .doesNotContain("SECRET_FIELD_VALUE");
    }

    @Test
    void malformedEventLogsMalformedStatusAndReasonWithoutPayloadDump() {
        var logs = captureLogs(() -> pipeline().process(AdoWebhookEvent.workItemUpdated("org", " ", 123L, "Test Case",
                27, "Human User", "human@example.com", Set.of("SECRET_FIELD_VALUE")), config(true, "Test Case")));

        assertThat(logs).contains("FAILED_MALFORMED_EVENT").contains("Project is missing.")
                .doesNotContain("SECRET_FIELD_VALUE");
    }

    @Test
    void patchFailureLogsFailureStatusAndRetryabilityWithoutRawFieldValues() {
        var adoClient = fakeAdoClient();
        adoClient.patchResult = AdoPatchResult.retryableFailure("conflict");

        var logs = captureLogs(() -> processingService(adoClient, new CommentBuilder()).process(command()));

        assertThat(logs).contains("Patch failed").contains("retryable=true").contains("FAILED_RETRYABLE")
                .doesNotContain("SECRET_FIELD_VALUE");
    }

    @Test
    void commentFailureLogsCompletedWithWarningWithoutCommentTextOrFieldValues() {
        var adoClient = fakeAdoClient();
        adoClient.commentResult = AdoCommentResult.failure("comment service unavailable");

        var logs = captureLogs(() -> processingService(adoClient, new SensitiveCommentBuilder()).process(command()));

        assertThat(logs).contains("Comment failed after successful patch").contains("COMPLETED_WITH_WARNING")
                .doesNotContain("SECRET_COMMENT_TEXT").doesNotContain("SECRET_FIELD_VALUE");
    }

    @Test
    void detailedRejectedValuesAppearInCommentButNotLogs() {
        var currentFields = new HashMap<String, Object>();
        currentFields.put("System.State", "In Review");
        currentFields.put("System.Title", "SECRET_REJECTED_PROPOSED");
        var previousFields = new HashMap<String, Object>();
        previousFields.put("System.State", "In Review");
        previousFields.put("System.Title", "SECRET_REJECTED_PREVIOUS");
        var adoClient = new FakeAdoClient(
                new AdoWorkItem(123, "ProjectA", "Test Case", 10, "In Review", currentFields),
                new AdoWorkItemRevision(123, 9, new AdoIdentity("Human User", "human@example.com"), previousFields,
                        previousFields.keySet()));

        var logs = captureLogs(() -> processingService(adoClient, new CommentBuilder()).process(command()));

        assertThat(adoClient.commentText).contains("SECRET_REJECTED_PREVIOUS")
                .contains("SECRET_REJECTED_PROPOSED");
        assertThat(logs).doesNotContain("SECRET_REJECTED_PREVIOUS").doesNotContain("SECRET_REJECTED_PROPOSED");
    }

    @Test
    void idempotentDuplicateLogsDuplicateSkip() {
        var store = new InMemoryProcessedEventStore(Duration.ofHours(1), 10);
        var delegate = processingService(fakeAdoClient(), new CommentBuilder());
        var processor = new IdempotentWorkItemProcessor(store, delegate);

        var logs = captureLogs(() -> {
            processor.process(command());
            var duplicate = processor.process(command());
            assertThat(duplicate.result().name()).isEqualTo("SKIPPED");
        });

        assertThat(logs).contains("Work item event marked processed").contains("Duplicate work item event skipped")
                .contains("project=ProjectA").contains("workItemId=123").contains("revision=10");
    }

    private WebhookEventProcessingPipeline pipeline() {
        var queueProcessor = new QueuedWorkItemProcessor(new InMemoryWorkItemQueue(),
                command -> WorkItemProcessingResult.completed("done", null));
        return new WebhookEventProcessingPipeline(new EventClassifier("org"), queueProcessor);
    }

    private AdoWebhookEvent event(String project, String workItemType, String changedByEmail) {
        return AdoWebhookEvent.workItemUpdated("org", project, 123L, workItemType, 10, "Human User", changedByEmail,
                Set.of());
    }

    private WorkItemProcessingService processingService(FakeAdoClient adoClient, CommentBuilder commentBuilder) {
        return new WorkItemProcessingService(adoClient, new WorkflowEngine(), new PatchBuilder(), commentBuilder);
    }

    private ProcessWorkItemCommand command() {
        return new ProcessWorkItemCommand(KEY, 10, config(true, "Test Case"));
    }

    private ProjectApprovalConfig config(boolean enabled, String... supportedTypes) {
        return new ProjectApprovalConfig("ProjectA", enabled, Set.of(supportedTypes), "Custom.ApprovedBySME",
                "Custom.ApprovedBySQA", Set.of("System.Title"), Set.of("sme@example.com"), Set.of("sqa@example.com"),
                "bot@example.com");
    }

    private FakeAdoClient fakeAdoClient() {
        var fields = new HashMap<String, Object>();
        fields.put("System.State", "Approved");
        fields.put("System.WorkItemType", "Test Case");
        fields.put("System.Title", "SECRET_FIELD_VALUE");
        fields.put("Custom.ApprovedBySME", null);
        fields.put("Custom.ApprovedBySQA", null);

        var previousFields = new HashMap<String, Object>();
        previousFields.put("System.State", "In Review");
        previousFields.put("System.Title", "old value");

        return new FakeAdoClient(new AdoWorkItem(123, "ProjectA", "Test Case", 10, "Approved", fields),
                new AdoWorkItemRevision(123, 9, new AdoIdentity("Human User", "human@example.com"), previousFields,
                        previousFields.keySet()));
    }

    private String captureLogs(Runnable action) {
        var root = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        var previousLevel = root.getLevel();
        var appender = new ListAppender<ILoggingEvent>();
        appender.start();
        root.addAppender(appender);
        root.setLevel(Level.DEBUG);
        try {
            action.run();
            return appender.list.stream().map(ILoggingEvent::getFormattedMessage).reduce("",
                    (left, right) -> left + "\n" + right);
        } finally {
            root.detachAppender(appender);
            root.setLevel(previousLevel);
        }
    }

    private static class SensitiveCommentBuilder extends CommentBuilder {

        @Override
        public Optional<String> fromDecision(WorkflowDecision decision) {
            return Optional.of("SECRET_COMMENT_TEXT");
        }
    }

    private static class FakeAdoClient implements AdoClient {

        private final AdoWorkItem workItem;
        private final AdoWorkItemRevision revision;
        private AdoPatchResult patchResult = AdoPatchResult.success(11);
        private AdoCommentResult commentResult = AdoCommentResult.success("comment-1");
        private String commentText;

        private FakeAdoClient(AdoWorkItem workItem, AdoWorkItemRevision revision) {
            this.workItem = workItem;
            this.revision = revision;
        }

        @Override
        public AdoWorkItem fetchWorkItem(AdoWorkItemKey key) {
            return workItem;
        }

        @Override
        public AdoWorkItemRevision fetchWorkItemRevision(AdoWorkItemKey key, int revision) {
            return this.revision;
        }

        @Override
        public AdoPatchResult patchWorkItem(AdoWorkItemKey key, List<PatchOperation> patchOperations) {
            return patchResult;
        }

        @Override
        public AdoCommentResult createWorkItemComment(AdoWorkItemKey key, String commentText) {
            this.commentText = commentText;
            return commentResult;
        }
    }
}
