package com.dentalwings.approvalbot.webhook;

import com.dentalwings.approvalbot.ado.AdoWorkItemKey;
import com.dentalwings.approvalbot.config.ProjectApprovalConfig;
import com.dentalwings.approvalbot.identity.EmailNormalizer;

public class EventClassifier {

    private final EmailNormalizer emailNormalizer = new EmailNormalizer();

    public EventClassification classify(AdoWebhookEvent event, ProjectApprovalConfig projectConfig) {
        if (event == null || event.resource() == null) {
            return EventClassification.malformed("Webhook event resource is missing.");
        }

        var resource = event.resource();
        if (isBlank(resource.project())) {
            return EventClassification.malformed("Project is missing.");
        }
        if (resource.workItemId() == null) {
            return EventClassification.malformed("Work item id is missing.");
        }
        if (resource.workItemId() <= 0) {
            return EventClassification.malformed("Work item id is invalid.");
        }
        if (resource.revision() == null) {
            return EventClassification.malformed("Revision is missing.");
        }
        if (resource.revision() <= 0) {
            return EventClassification.malformed("Revision is invalid.");
        }
        if (projectConfig == null || !projectConfig.enabled()) {
            return EventClassification.skipped(EventClassificationStatus.SKIPPED_DISABLED_PROJECT, "Project is disabled.");
        }
        if (!projectConfig.supportedWorkItemTypes().contains(resource.workItemType())) {
            return EventClassification.skipped(EventClassificationStatus.SKIPPED_UNSUPPORTED_WORK_ITEM_TYPE, "Work item type is unsupported.");
        }
        if (isBotEvent(resource, projectConfig)) {
            return EventClassification.skipped(EventClassificationStatus.SKIPPED_BOT_EVENT, "Event was generated by the bot.");
        }

        return EventClassification.processable(
                new AdoWorkItemKey(event.organization(), resource.project(), resource.workItemId()),
                resource.revision()
        );
    }

    private boolean isBotEvent(AdoWebhookResource resource, ProjectApprovalConfig projectConfig) {
        var botEmail = emailNormalizer.normalize(projectConfig.botIdentityEmail());
        var changedByEmail = emailNormalizer.normalize(resource.changedByEmailOrLogin());
        return botEmail.isPresent() && botEmail.equals(changedByEmail);
    }

    private boolean isBlank(String value) {
        return value == null || value.isBlank();
    }
}
