ado:
  organization: STMN-Group
  authentication:
    mode: bearer
    bearer-token: ${ADO_ACCESS_TOKEN:}
  http-client-enabled: true
  dry-run: true
  projects:
    "[ADOnis 2.0 Test Project]":
      enabled: true
      supported-work-item-types:
        - Test Case
      states:
        design: Design
        in-review: In Review
        approved: Approval
      fields:
        approved-by-sme: Custom.ApproverTech
        approved-by-sqa: Custom.ApproverTest
        reversible-business-fields:
          - System.Title
          - System.Description
          - Microsoft.VSTS.TCM.Steps
          - Microsoft.VSTS.TCM.LocalDataSource
      approvals:
        sme-users:
          - u129670@straumann.com
        sqa-users:
          - u116727@straumann.com

bot:
  identity-email: ado-approval-bot-sandbox@straumann.com
