package com.dentalwings.approvalbot.workflow;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.dentalwings.approvalbot.config.ProjectApprovalConfig;
import com.dentalwings.approvalbot.config.WorkflowStateNames;
import com.dentalwings.approvalbot.domain.Identity;
import com.dentalwings.approvalbot.domain.PatchOperation;
import com.dentalwings.approvalbot.domain.WorkflowDecision;
import com.dentalwings.approvalbot.domain.WorkflowInput;
import com.dentalwings.approvalbot.identity.EmailNormalizer;
import com.dentalwings.approvalbot.identity.IdentityClassification;
import com.dentalwings.approvalbot.identity.IdentityClassifier;
import com.dentalwings.approvalbot.workflow.comment.CommentBuilder;
import com.dentalwings.approvalbot.workflow.comment.CommentBuilder.RejectedChange;

public class WorkflowEngine
{

    public static final String STATE_DESIGN = WorkflowStateNames.DEFAULT_DESIGN;
    public static final String STATE_IN_REVIEW = WorkflowStateNames.DEFAULT_IN_REVIEW;
    public static final String STATE_APPROVED = WorkflowStateNames.DEFAULT_APPROVED;
    public static final String WORK_ITEM_TYPE_TEST_CASE = "Test Case";
    public static final String SYSTEM_STATE = "System.State";

    private final ChangeAnalyzer changeAnalyzer;
    private final ApprovalValidator approvalValidator;
    private final ApprovalValueParser approvalValueParser;
    private final IdentityClassifier identityClassifier;
    private final EmailNormalizer emailNormalizer;
    private final ValueComparator valueComparator;
    private final CommentBuilder commentBuilder;

    public WorkflowEngine()
    {
        this(new CommentBuilder());
    }

    public WorkflowEngine(CommentBuilder commentBuilder)
    {
        this.commentBuilder = Objects.requireNonNull(commentBuilder);
        this.emailNormalizer = new EmailNormalizer();
        this.valueComparator = new ValueComparator();
        this.changeAnalyzer = new ChangeAnalyzer(valueComparator);
        this.approvalValueParser = new ApprovalValueParser(emailNormalizer);
        this.approvalValidator = new ApprovalValidator(approvalValueParser, emailNormalizer);
        this.identityClassifier = new IdentityClassifier(emailNormalizer);
    }

    public WorkflowDecision decide(WorkflowInput input)
    {
        var config = input.projectConfig();
        var stateNames = config == null ? WorkflowStateNames.defaults() : config.stateNames();
        if (config == null || !config.enabled())
        {
            return WorkflowDecision.skipped("Project is disabled.");
        }
        if (isBotGenerated(input.changedBy(), config))
        {
            return WorkflowDecision.skipped("Event was generated by the bot.");
        }
        if (!config.supportedWorkItemTypes().contains(input.workItemType()))
        {
            return WorkflowDecision.skipped("Work item type is unsupported.");
        }
        if (!isKnownState(input.currentState(), stateNames))
        {
            return WorkflowDecision.skipped("Current state is out of scope.");
        }

        if (stateEquals(stateNames.design(), input.previousState())
                && stateEquals(stateNames.approved(), input.currentState()))
        {
            return designToApprovedCorrection(config);
        }
        if (stateEquals(stateNames.design(), input.currentState()))
        {
            return handleDesign(input, config);
        }
        if (stateEquals(stateNames.inReview(), input.currentState()))
        {
            return handleInReview(input, config);
        }
        if (stateEquals(stateNames.approved(), input.currentState()))
        {
            return handleApproved(input, config);
        }

        return WorkflowDecision.skipped("No workflow action required.");
    }

    private WorkflowDecision handleDesign(WorkflowInput input, ProjectApprovalConfig config)
    {
        var operations = clearApprovalsIfPresent(input.currentFields(), config);
        if (operations.isEmpty())
        {
            return WorkflowDecision.skipped("Design state has no approval fields to clear.");
        }
        return WorkflowDecision.completed(operations, null, "Design state clears approval fields.");
    }

    private WorkflowDecision designToApprovedCorrection(ProjectApprovalConfig config)
    {
        var operations = new ArrayList<PatchOperation>();
        operations.add(PatchOperation.replaceField(SYSTEM_STATE, config.stateNames().inReview()));
        operations.add(clearApprovalField(config.approvedBySmeField()));
        operations.add(clearApprovalField(config.approvedBySqaField()));
        return WorkflowDecision.completed(operations, """
                        The Test Case was returned to In Review because it cannot move directly from Design to Approved.
                        
                                Approval requires review by valid SME and SQA approvers.""",
                "Design cannot move directly to Approved.");
    }

    private WorkflowDecision handleInReview(WorkflowInput input, ProjectApprovalConfig config)
    {
        var changedReversibleFields = changeAnalyzer.changedReversibleFields(input.previousFields(),
                input.currentFields(), config);
        var approvalRejections = approvalFieldRejections(input, config, false);
        var classification = identityClassifier.classify(input.changedBy(), config);

        if (!changedReversibleFields.isEmpty() && !classification.authorizedApprover())
        {
            var operations = new ArrayList<PatchOperation>();
            changedReversibleFields.stream()
                    .map(field -> PatchOperation.replaceField(field, input.previousFields().get(field)))
                    .forEach(operations::add);
            operations.addAll(restoreChangedApprovalFields(input, config));
            var rejectedChanges = new ArrayList<>(reversibleFieldRejections(input, changedReversibleFields));
            rejectedChanges.addAll(approvalRejections);
            return WorkflowDecision.completed(operations,
                    commentBuilder.unauthorizedModifications(input.changedBy(), rejectedChanges),
                    "Unauthorized reversible content changes were reverted.");
        }

        if (!changedReversibleFields.isEmpty())
        {
            var operations = new ArrayList<PatchOperation>();
            operations.add(clearApprovalField(config.approvedBySmeField()));
            operations.add(clearApprovalField(config.approvedBySqaField()));
            operations.addAll(currentUserApprovalOperations(input.changedBy(), classification, config, Map.of()));
            var approvalCorrections = approvalFieldRejections(input, config, true);
            return WorkflowDecision.completed(operations,
                    detailedCorrectionComment(input.changedBy(), approvalCorrections),
                    "Authorized content change resets approvals and records current reviewer.");
        }

        if (classification.authorizedApprover())
        {
            return finalizeInReviewApprovals(input, config, classification);
        }

        var approvalRestores = restoreChangedApprovalFields(input, config);
        if (!approvalRestores.isEmpty())
        {
            return WorkflowDecision.completed(approvalRestores,
                    detailedCorrectionComment(input.changedBy(), approvalRejections),
                    "Manual approval field edit was ignored.");
        }

        return finalizeInReviewApprovals(input, config, classification);
    }

    private WorkflowDecision finalizeInReviewApprovals(WorkflowInput input, ProjectApprovalConfig config,
            IdentityClassification classification)
    {
        var projectedFields = fieldsWithTrustedApprovals(input, config);
        var validationFields = new LinkedHashMap<>(projectedFields);
        var operations = new ArrayList<>(restoreChangedApprovalFields(input, config));
        var correctionComment = detailedCorrectionComment(input.changedBy(),
                approvalFieldRejections(input, config, false));

        applyCurrentUserApproval(input, config, classification, operations, projectedFields, validationFields);

        var validation = approvalValidator.validate(validationFields, config);
        if (hasValue(projectedFields.get(config.approvedBySmeField())) && !validation.validSme())
        {
            addProjectedOperation(clearApprovalField(config.approvedBySmeField()), operations, projectedFields,
                    validationFields, input.changedBy(), config);
        }
        if (hasValue(projectedFields.get(config.approvedBySqaField())) && !validation.validSqa())
        {
            addProjectedOperation(clearApprovalField(config.approvedBySqaField()), operations, projectedFields,
                    validationFields, input.changedBy(), config);
        }

        validation = approvalValidator.validate(validationFields, config);
        var sameApprovalEmail = validation.smeEmail().isPresent()
                && validation.smeEmail().equals(validation.sqaEmail());
        if (sameApprovalEmail)
        {
            addProjectedOperation(clearApprovalField(config.approvedBySqaField()), operations, projectedFields,
                    validationFields, input.changedBy(), config);
            validation = approvalValidator.validate(validationFields, config);
        }

        if (validation.fullyApprovedByDifferentUsers())
        {
            operations.add(PatchOperation.replaceField(SYSTEM_STATE, config.stateNames().approved()));
            return WorkflowDecision.completed(operations,
                    combineComments(correctionComment, approvedComment(projectedFields, config)),
                    "Approvals are valid and complete.");
        }

        if (operations.isEmpty())
        {
            return WorkflowDecision.skipped("Approval already reflects current reviewer.");
        }
        return WorkflowDecision.completed(operations, correctionComment, "Current reviewer approval was recorded.");
    }

    private void addProjectedOperation(PatchOperation operation, List<PatchOperation> operations,
            Map<String, Object> projectedFields, Map<String, Object> validationFields, Identity changedBy,
            ProjectApprovalConfig config)
    {
        operations.add(operation);
        var field = operation.path().replace("/fields/", "");
        projectedFields.put(field, operation.value());
        validationFields.put(field, logicalApprovalValueForValidation(field, operation.value(), changedBy, config));
    }

    private WorkflowDecision handleApproved(WorkflowInput input, ProjectApprovalConfig config)
    {
        var projectedFields = fieldsWithTrustedApprovals(input, config);
        var validationFields = new LinkedHashMap<>(projectedFields);
        var operations = new ArrayList<>(restoreChangedApprovalFields(input, config));
        var correctionComment = detailedCorrectionComment(input.changedBy(),
                approvalFieldRejections(input, config, false));
        var classification = identityClassifier.classify(input.changedBy(), config);
        applyCurrentUserApproval(input, config, classification, operations, projectedFields, validationFields);

        var validation = approvalValidator.validate(validationFields, config);
        if (validation.fullyApprovedByDifferentUsers())
        {
            if (!operations.isEmpty())
            {
                return WorkflowDecision.completed(operations, correctionComment,
                        "Approved state approval fields were restored from trusted values.");
            }
            return WorkflowDecision.skipped("Approved state already has valid approvals.");
        }

        var sameApprovalEmail = validation.smeEmail().isPresent()
                && validation.smeEmail().equals(validation.sqaEmail());
        if (!validation.validSme() && !containsClearOperation(operations, config.approvedBySmeField()))
        {
            addProjectedOperation(clearApprovalField(config.approvedBySmeField()), operations, projectedFields,
                    validationFields, input.changedBy(), config);
        }
        if ((!validation.validSqa() || sameApprovalEmail)
                && !containsClearOperation(operations, config.approvedBySqaField()))
        {
            addProjectedOperation(clearApprovalField(config.approvedBySqaField()), operations, projectedFields,
                    validationFields, input.changedBy(), config);
        }
        var correctionOperations = new ArrayList<PatchOperation>();
        correctionOperations.add(PatchOperation.replaceField(SYSTEM_STATE, config.stateNames().inReview()));
        correctionOperations.addAll(operations);
        return WorkflowDecision.completed(correctionOperations, combineComments(correctionComment,
                "The Test Case was returned to In Review because it does not have valid SME and SQA approvals from different users."),
                "Approved state has invalid approvals.");
    }

    private List<RejectedChange> approvalFieldRejections(WorkflowInput input, ProjectApprovalConfig config,
            boolean approvalsResetForContentChange)
    {
        var rejectedChanges = new ArrayList<RejectedChange>();
        addApprovalFieldRejection(input, config.approvedBySmeField(), approvalsResetForContentChange,
                rejectedChanges);
        addApprovalFieldRejection(input, config.approvedBySqaField(), approvalsResetForContentChange,
                rejectedChanges);
        return List.copyOf(rejectedChanges);
    }

    private void addApprovalFieldRejection(WorkflowInput input, String field, boolean approvalsResetForContentChange,
            List<RejectedChange> rejectedChanges)
    {
        if (!Objects.deepEquals(input.previousFields().get(field), input.currentFields().get(field)))
        {
            var previousValue = input.previousFields().get(field);
            var actionTaken = approvalFieldAction(previousValue, approvalsResetForContentChange);
            rejectedChanges.add(new RejectedChange(field, input.previousFields().get(field),
                    input.currentFields().get(field),
                    "Approval fields are bot-owned; manually supplied identity values are not trusted.", actionTaken));
        }
    }

    private String approvalFieldAction(Object previousValue, boolean approvalsResetForContentChange)
    {
        if (approvalsResetForContentChange)
        {
            return "Discarded the manual approval value while approvals were reset and recalculated from the actual modifier identity.";
        }
        return hasValue(previousValue) ? "Restored the previous bot-owned approval value."
                : "Cleared the approval field because no previous bot-owned value existed.";
    }

    private List<RejectedChange> reversibleFieldRejections(WorkflowInput input, Iterable<String> fields)
    {
        var rejectedChanges = new ArrayList<RejectedChange>();
        for (String field : fields)
        {
            rejectedChanges.add(new RejectedChange(field, input.previousFields().get(field),
                    input.currentFields().get(field),
                    "The field is configured as reversible-business-fields and the modifier is not an authorized SME/SQA approver.",
                    "Reverted the configured field to its previous value."));
        }
        return List.copyOf(rejectedChanges);
    }

    private String detailedCorrectionComment(Identity changedBy, List<RejectedChange> rejectedChanges)
    {
        return rejectedChanges.isEmpty() ? null
                : commentBuilder.unauthorizedModifications(changedBy, rejectedChanges);
    }

    private String combineComments(String first, String second)
    {
        if (first == null || first.isBlank())
        {
            return second;
        }
        if (second == null || second.isBlank())
        {
            return first;
        }
        return first + "\n\n" + second;
    }

    private LinkedHashMap<String, Object> fieldsWithTrustedApprovals(WorkflowInput input,
            ProjectApprovalConfig config)
    {
        var trustedFields = new LinkedHashMap<>(input.currentFields());
        trustedFields.put(config.approvedBySmeField(), input.previousFields().get(config.approvedBySmeField()));
        trustedFields.put(config.approvedBySqaField(), input.previousFields().get(config.approvedBySqaField()));
        return trustedFields;
    }

    private void applyCurrentUserApproval(WorkflowInput input, ProjectApprovalConfig config,
            IdentityClassification classification, List<PatchOperation> operations, Map<String, Object> projectedFields,
            Map<String, Object> validationFields)
    {
        if (!classification.authorizedApprover())
        {
            return;
        }
        for (PatchOperation operation : currentUserApprovalOperations(input.changedBy(), classification, config,
                projectedFields))
        {
            addProjectedOperation(operation, operations, projectedFields, validationFields, input.changedBy(), config);
        }
    }

    private boolean containsClearOperation(List<PatchOperation> operations, String field)
    {
        return operations.contains(clearApprovalField(field));
    }

    private List<PatchOperation> clearApprovalsIfPresent(Map<String, Object> fields, ProjectApprovalConfig config)
    {
        var operations = new ArrayList<PatchOperation>();
        if (hasValue(fields.get(config.approvedBySmeField())))
        {
            operations.add(clearApprovalField(config.approvedBySmeField()));
        }
        if (hasValue(fields.get(config.approvedBySqaField())))
        {
            operations.add(clearApprovalField(config.approvedBySqaField()));
        }
        return operations;
    }

    private Object logicalApprovalValueForValidation(String field, Object value, Identity changedBy,
            ProjectApprovalConfig config)
    {
        if (value == null || !hasValue(value))
        {
            return null;
        }
        if (field.equals(config.approvedBySmeField()) || field.equals(config.approvedBySqaField()))
        {
            return emailNormalizer.normalize(changedBy.email()).orElse(value.toString());
        }
        return value;
    }

    private List<PatchOperation> currentUserApprovalOperations(Identity changedBy,
            IdentityClassification classification, ProjectApprovalConfig config, Map<String, Object> projectedFields)
    {
        var approvalValue = approvalIdentityWriteValue(changedBy);
        if (approvalValue == null)
        {
            return List.of();
        }
        if (classification.sme())
        {
            var currentEmail = emailNormalizer.normalize(changedBy.email()).orElse(null);
            var existingSme = approvalValueParser.extractEmail(projectedFields.get(config.approvedBySmeField()));
            var existingSqa = approvalValueParser.extractEmail(projectedFields.get(config.approvedBySqaField()));
            if (currentEmail != null && (existingSme.filter(currentEmail::equals).isPresent()
                    || existingSqa.filter(currentEmail::equals).isPresent()))
            {
                return List.of();
            }
            if (classification.sqa() && hasValue(projectedFields.get(config.approvedBySmeField()))
                    && !hasValue(projectedFields.get(config.approvedBySqaField())))
            {
                return List.of(PatchOperation.replaceField(config.approvedBySqaField(), approvalValue));
            }
            return List.of(PatchOperation.replaceField(config.approvedBySmeField(), approvalValue));
        }
        if (classification.sqa())
        {
            var currentEmail = emailNormalizer.normalize(changedBy.email()).orElse(null);
            var existingSme = approvalValueParser.extractEmail(projectedFields.get(config.approvedBySmeField()));
            var existingSqa = approvalValueParser.extractEmail(projectedFields.get(config.approvedBySqaField()));
            if (currentEmail != null && (existingSme.filter(currentEmail::equals).isPresent()
                    || existingSqa.filter(currentEmail::equals).isPresent()))
            {
                return List.of();
            }
            return List.of(PatchOperation.replaceField(config.approvedBySqaField(), approvalValue));
        }
        return List.of();
    }

    private List<PatchOperation> restoreChangedApprovalFields(WorkflowInput input, ProjectApprovalConfig config)
    {
        var operations = new ArrayList<PatchOperation>();
        restoreApprovalFieldIfChanged(input, config.approvedBySmeField(), operations);
        restoreApprovalFieldIfChanged(input, config.approvedBySqaField(), operations);
        return operations;
    }

    private void restoreApprovalFieldIfChanged(WorkflowInput input, String field, List<PatchOperation> operations)
    {
        if (!Objects.deepEquals(input.previousFields().get(field), input.currentFields().get(field)))
        {
            var previousValue = input.previousFields().get(field);
            operations.add(hasValue(previousValue) ? PatchOperation.replaceField(field, previousValue)
                    : clearApprovalField(field));
        }
    }

    private PatchOperation clearApprovalField(String field)
    {
        return PatchOperation.replaceField(field, "");
    }

    private boolean isBotGenerated(Identity changedBy, ProjectApprovalConfig config)
    {
        if (changedBy == null)
        {
            return false;
        }
        var botEmail = emailNormalizer.normalize(config.botIdentityEmail());
        var changedByEmail = emailNormalizer.normalize(changedBy.email());
        return botEmail.isPresent() && botEmail.equals(changedByEmail);
    }

    private String approvalIdentityWriteValue(Identity identity)
    {
        if (identity == null)
        {
            return null;
        }
        if (identity.displayName() != null && !identity.displayName().isBlank())
        {
            return identity.displayName().trim();
        }
        return emailNormalizer.normalize(identity.email()).orElse(null);
    }

    private String approvedComment(Map<String, Object> fields, ProjectApprovalConfig config)
    {
        return """
                Test Case approved automatically.
                
                Approved by SME:
                %s
                
                Approved by SQA:
                %s""".formatted(fields.get(config.approvedBySmeField()), fields.get(config.approvedBySqaField()));
    }

    private boolean hasValue(Object value)
    {
        return value != null && !value.toString().trim().isEmpty();
    }

    private boolean isKnownState(String state, WorkflowStateNames stateNames)
    {
        return stateEquals(stateNames.design(), state) || stateEquals(stateNames.inReview(), state)
                || stateEquals(stateNames.approved(), state);
    }

    private boolean stateEquals(String configuredState, String actualState)
    {
        return Objects.equals(configuredState, actualState);
    }
}
